#spring:
#  security:
#    user:
#      name: user1
#spring:
#  security:
#    user:
#      password: password1

spring:
  thymeleaf:
    cache: false

error:
  whitelabel:
    enabled: false

amazon:
  associate_id: gg

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG